# Generated by Django 2.1.1 on 2018-11-05 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='pub_date',
            field=models.DateField(auto_now=True, verbose_name='Publication date'),
        ),
    ]
