# Generated by Django 2.1.1 on 2018-11-22 02:49

from django.db import migrations, models
import news.models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_news_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='picture',
            field=models.ImageField(default='', upload_to=news.models.News.picture_news, verbose_name='Picture'),
            preserve_default=False,
        ),
    ]
