# Generated by Django 2.1.1 on 2018-10-16 00:59

from django.db import migrations, models
import services.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ci', models.CharField(max_length=13, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=150)),
                ('born_date', models.DateField()),
                ('civil_status', models.CharField(choices=[('c', 'Casado'), ('v', 'Viudo'), ('s', 'Soltero')], max_length=1)),
                ('naturalness', models.CharField(max_length=30, verbose_name='Naturalidad')),
                ('nationality', models.CharField(max_length=30, verbose_name='Nacionalidad')),
                ('father', models.CharField(max_length=200)),
                ('mother', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.PositiveIntegerField(verbose_name='Numero de telefono')),
                ('data_attachment', models.FileField(upload_to=services.models.Client.upload_file, verbose_name='Ficheros adjuntos')),
            ],
        ),
        migrations.CreateModel(
            name='Visto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especification', models.CharField(max_length=100, verbose_name='especificacion')),
                ('pedido_prorroga_anos', models.DateField(verbose_name='Pedido de prorroga')),
                ('tipo_solicitud', models.CharField(max_length=100, verbose_name='Tipo de solicitud')),
                ('pasaporte_no', models.CharField(max_length=100, verbose_name='No. de Pasaporte')),
                ('fecha_emision_pasaporte', models.DateField(verbose_name='Fecha de emision de pasaporte')),
                ('fecha_vencimiento_pasaporte', models.DateField(verbose_name='Fecha de vencimiento de pasaporte')),
                ('visto_no', models.CharField(max_length=100, verbose_name='No. de Visto')),
                ('fecha_emision_visto', models.DateField(verbose_name='Fecha de emision de Visto')),
                ('fecha_vencimiento_visto', models.DateField(verbose_name='Fecha de vencimiento de Visto')),
            ],
        ),
    ]
