# Generated by Django 2.1.1 on 2018-10-20 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='client',
            name='civil_status',
            field=models.CharField(choices=[('s', 'Soltero'), ('o', 'Comprometido'), ('c', 'Casado'), ('v', 'Viudo')], max_length=1),
        ),
        migrations.CreateModel(
            name='Visa',
            fields=[
                ('service_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='services.Service')),
                ('specification', models.CharField(choices=[('VT', ''), ('VPT', ''), ('VP', ''), ('VE', ''), ('VTM', ''), ('VOR', ''), ('VTU', ''), ('VCD', '')], max_length=3, verbose_name='especificacion')),
                ('extension_request_date', models.DateField(verbose_name='Pedido de prorroga')),
                ('request_type', models.CharField(choices=[('C', 'Caducidad'), ('E', 'Extravio')], max_length=1, verbose_name='Tipo de solicitud')),
                ('passport_no', models.CharField(max_length=100, verbose_name='No. de Pasaporte')),
                ('passport_issuance_date', models.DateField(verbose_name='Fecha de emision de pasaporte')),
                ('passport_expiration_date', models.DateField(verbose_name='Fecha de vencimiento de pasaporte')),
                ('visa_no', models.CharField(max_length=100, verbose_name='No. de Visa')),
                ('visa_issuance_date', models.DateField(verbose_name='Fecha de emision de Visa')),
                ('visa_expiration_date', models.DateField(verbose_name='Fecha de vencimiento de Visa')),
                ('status', models.CharField(choices=[('1', 'Solicitud'), ('2', 'Facturacion'), ('3', 'Revision'), ('4', 'Autenticar'), ('5', 'Entrega')], max_length=1, verbose_name='Estado')),
            ],
            bases=('services.service',),
        ),
        migrations.AddField(
            model_name='service',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.Client'),
        ),
    ]
