# Generated by Django 2.1.1 on 2018-10-20 17:20

from django.db import migrations, models
import services.models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_auto_20181020_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='data_attachment',
            field=models.FileField(null=True, upload_to=services.models.Client.upload_file, verbose_name='Ficheros adjuntos'),
        ),
        migrations.AlterField(
            model_name='visa',
            name='specification',
            field=models.CharField(choices=[('VT', ''), ('VPT', ''), ('VP', ''), ('VE', ''), ('VTM', ''), ('VOR', ''), ('VTU', ''), ('VCD', 'Visado de corta duracion')], max_length=3, verbose_name='especificacion'),
        ),
    ]
