# Generated by Django 2.1.1 on 2018-10-20 17:27

from django.db import migrations, models
import services.models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_auto_20181020_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='civil_status',
            field=models.CharField(choices=[('s', 'Soltero'), ('e', 'Comprometido'), ('m', 'Casado'), ('w', 'Viudo')], max_length=1),
        ),
        migrations.AlterField(
            model_name='client',
            name='data_attachment',
            field=models.FileField(blank=True, null=True, upload_to=services.models.Client.upload_file, verbose_name='Ficheros adjuntos'),
        ),
    ]
