# Generated by Django 2.1.1 on 2018-10-20 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_auto_20181020_1327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visa',
            name='status',
        ),
        migrations.AddField(
            model_name='service',
            name='status',
            field=models.CharField(choices=[('1', 'Solicitud'), ('2', 'Facturacion'), ('3', 'Revision'), ('4', 'Autenticar'), ('5', 'Entrega')], default='Solicitud', max_length=1, verbose_name='Estado'),
            preserve_default=False,
        ),
    ]
