# Generated by Django 2.1.1 on 2018-10-21 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_auto_20181020_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visa',
            name='specification',
            field=models.CharField(choices=[('VT', 'VT'), ('VPT', 'VPT'), ('VP', 'VP'), ('VE', 'VE'), ('VTM', 'VTM'), ('VOR', 'VOR'), ('VTU', 'VTU'), ('VCD', 'Visado de corta duracion')], max_length=3, verbose_name='especificacion'),
        ),
    ]
