# Generated by Django 2.1.1 on 2018-10-21 20:03

from django.db import migrations, models
import django.db.models.deletion
import services.models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_auto_20181020_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='address',
            field=models.TextField(verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='client',
            name='born_date',
            field=models.DateField(verbose_name='Born date'),
        ),
        migrations.AlterField(
            model_name='client',
            name='ci',
            field=models.CharField(max_length=13, unique=True, verbose_name='Identity card'),
        ),
        migrations.AlterField(
            model_name='client',
            name='civil_status',
            field=models.CharField(choices=[('S', 'Single'), ('E', 'Engaged'), ('M', 'Married'), ('W', 'Widower')], max_length=1, verbose_name='Civil status'),
        ),
        migrations.AlterField(
            model_name='client',
            name='data_attachment',
            field=models.FileField(blank=True, null=True, upload_to=services.models.Client.upload_file, verbose_name='Data attachment'),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='client',
            name='father',
            field=models.CharField(max_length=200, verbose_name='Father name'),
        ),
        migrations.AlterField(
            model_name='client',
            name='first_name',
            field=models.CharField(max_length=30, verbose_name='First name'),
        ),
        migrations.AlterField(
            model_name='client',
            name='last_name',
            field=models.CharField(max_length=150, verbose_name='Last name'),
        ),
        migrations.AlterField(
            model_name='client',
            name='mother',
            field=models.CharField(max_length=200, verbose_name='Mother name'),
        ),
        migrations.AlterField(
            model_name='client',
            name='nationality',
            field=models.CharField(max_length=30, verbose_name='Nationality'),
        ),
        migrations.AlterField(
            model_name='client',
            name='naturalness',
            field=models.CharField(max_length=30, verbose_name='Naturalness'),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.PositiveIntegerField(verbose_name='Phone number'),
        ),
        migrations.AlterField(
            model_name='service',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.Client', verbose_name='Client'),
        ),
        migrations.AlterField(
            model_name='service',
            name='status',
            field=models.CharField(choices=[('1', 'Request'), ('2', 'Invoicing'), ('3', 'Revision'), ('4', 'Authenticating'), ('5', 'Deliver')], max_length=1, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='visa',
            name='extension_request_date',
            field=models.DateField(verbose_name='Extension request date'),
        ),
        migrations.AlterField(
            model_name='visa',
            name='passport_expiration_date',
            field=models.DateField(verbose_name='Passport expiration date'),
        ),
        migrations.AlterField(
            model_name='visa',
            name='passport_issuance_date',
            field=models.DateField(verbose_name='Passport issuance date'),
        ),
        migrations.AlterField(
            model_name='visa',
            name='passport_no',
            field=models.CharField(max_length=100, verbose_name='Passport No.'),
        ),
        migrations.AlterField(
            model_name='visa',
            name='request_type',
            field=models.CharField(choices=[('C', 'Caducity'), ('M', 'Misplacing')], max_length=1, verbose_name='Request type'),
        ),
        migrations.AlterField(
            model_name='visa',
            name='specification',
            field=models.CharField(choices=[('VT', 'VT'), ('VPT', 'VPT'), ('VP', 'VP'), ('VE', 'VE'), ('VTM', 'VTM'), ('VOR', 'VOR'), ('VTU', 'VTU'), ('VCD', 'Visa of short duration')], max_length=3, verbose_name='Specification'),
        ),
        migrations.AlterField(
            model_name='visa',
            name='visa_expiration_date',
            field=models.DateField(verbose_name='Visa expiration date'),
        ),
        migrations.AlterField(
            model_name='visa',
            name='visa_issuance_date',
            field=models.DateField(verbose_name='Visa issuance date'),
        ),
        migrations.AlterField(
            model_name='visa',
            name='visa_no',
            field=models.CharField(max_length=100, verbose_name='Visa No.'),
        ),
    ]
