# Generated by Django 2.1.1 on 2018-11-01 01:51

from django.db import migrations, models
import services.validators


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_auto_20181022_0851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='born_date',
            field=models.DateField(validators=[services.validators.validate_born_date], verbose_name='Born date'),
        ),
    ]
