# Generated by Django 2.1.1 on 2018-11-03 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_auto_20181031_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='status',
            field=models.CharField(choices=[('1', 'Request'), ('2', 'Invoicing'), ('3', 'Revision'), ('4', 'Authenticating'), ('5', 'Deliver')], default='1', max_length=1, verbose_name='Status'),
        ),
    ]
