# Generated by Django 2.1.1 on 2018-11-06 22:36

from django.db import migrations, models
import services.models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0010_auto_20181103_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=services.models.Client.upload_image, verbose_name='Picture'),
        ),
    ]
