# Generated by Django 2.1.1 on 2018-11-07 00:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0011_client_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Passport',
            fields=[
                ('service_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='services.Service')),
                ('passport_type', models.CharField(choices=[('N', 'Normal'), ('S', 'Service')], max_length=1, verbose_name='Passport type')),
                ('emission_date', models.DateField(verbose_name='Emission date')),
                ('remission_type', models.CharField(choices=[('C', 'Caducity'), ('M', 'Misplacing')], max_length=1, verbose_name='Remission type')),
                ('remission_date', models.DateField(verbose_name='Remission date')),
                ('personal_no', models.CharField(max_length=50, verbose_name='Personal No.')),
                ('passport_no', models.CharField(max_length=100, verbose_name='Passport No.')),
                ('passport_issuance_date', models.DateField(verbose_name='Passport issuance date')),
                ('passport_expiration_date', models.DateField(verbose_name='Passport expiration date')),
            ],
            bases=('services.service',),
        ),
    ]
