# Generated by Django 2.1.1 on 2018-11-10 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0012_passport'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('localization', models.CharField(max_length=200, verbose_name='Localization')),
                ('identification_no', models.CharField(max_length=50, verbose_name='Identification No.')),
                ('emission_date', models.DateField(verbose_name='Emission date')),
                ('issuance_date', models.DateField(verbose_name='Issuance date')),
                ('telephone', models.PositiveIntegerField(verbose_name='Telephone')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
            ],
        ),
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'Client', 'verbose_name_plural': 'Clients'},
        ),
        migrations.AlterModelOptions(
            name='passport',
            options={'verbose_name': 'passport', 'verbose_name_plural': 'passports'},
        ),
        migrations.AlterModelOptions(
            name='visa',
            options={'verbose_name': 'Visa', 'verbose_name_plural': 'Visas'},
        ),
    ]
