# Generated by Django 2.1.1 on 2018-11-10 03:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0013_auto_20181109_2245'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entity',
            options={'verbose_name': 'Entity', 'verbose_name_plural': 'Entities'},
        ),
        migrations.RemoveField(
            model_name='entity',
            name='emission_date',
        ),
        migrations.AddField(
            model_name='entity',
            name='expiration_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Expiration date'),
            preserve_default=False,
        ),
    ]
