# Generated by Django 2.1.1 on 2018-11-10 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0014_auto_20181109_2257'),
    ]

    operations = [
        migrations.AddField(
            model_name='visa',
            name='tutelary_entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='services.Entity'),
        ),
    ]
