# Generated by Django 2.1.1 on 2018-11-10 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0015_visa_tutelary_entity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visa',
            name='tutelary_entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='services.Entity', verbose_name='Tutelary Entity'),
        ),
    ]
