# Generated by Django 2.1.1 on 2018-11-14 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0016_auto_20181110_1615'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResidenceAuthorization',
            fields=[
                ('service_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='services.Service')),
                ('authorization_no', models.PositiveIntegerField(verbose_name='Authorization No.')),
                ('issued_place', models.CharField(max_length=100, verbose_name='Issued in')),
                ('issuance_date', models.DateField(verbose_name='Issuance date')),
                ('valid_date', models.DateField(verbose_name='Valid until')),
                ('passport_no', models.CharField(max_length=20, verbose_name='Passport No.')),
                ('passport_issuance_date', models.DateField(verbose_name='Passport issuance date')),
                ('passport_expiration_date', models.DateField(verbose_name='Passport expiration date')),
            ],
            bases=('services.service',),
        ),
        migrations.CreateModel(
            name='ResidenceMarriage',
            fields=[
                ('service_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='services.Service')),
                ('married_to', models.CharField(max_length=100, verbose_name='Married to')),
                ('ci', models.CharField(max_length=13, verbose_name='Identity card')),
                ('issuance_date', models.DateField(verbose_name='Issuance date')),
                ('valid_date', models.DateField(verbose_name='Valid date')),
            ],
            bases=('services.service',),
        ),
        migrations.CreateModel(
            name='ResidenceRenovation',
            fields=[
                ('service_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='services.Service')),
                ('residence_authorization_no', models.CharField(max_length=100, verbose_name='Residence authorization No.')),
                ('issuance_date', models.DateField(verbose_name='Residence authorization issuance date')),
                ('expiration_date', models.DateField(verbose_name='Residence authorization expiration date')),
                ('reason', models.CharField(choices=[('C', 'Caducity'), ('M', 'Misplacing')], max_length=1, verbose_name='Renovation reason')),
                ('passport_no', models.CharField(max_length=20, verbose_name='Passport No.')),
                ('issuance_passport_date', models.DateField(verbose_name='Issuance passport date')),
                ('valid_passport_date', models.DateField(verbose_name='Valid passport date')),
            ],
            bases=('services.service',),
        ),
    ]
