# Generated by Django 2.1.1 on 2018-11-22 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0017_residenceauthorization_residencemarriage_residencerenovation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='residenceauthorization',
            options={'verbose_name': 'Residence authorization', 'verbose_name_plural': 'Residences authorization'},
        ),
        migrations.AlterModelOptions(
            name='residencemarriage',
            options={'verbose_name': 'Residence by Marriage', 'verbose_name_plural': 'Residences by Marriage'},
        ),
        migrations.AlterModelOptions(
            name='residencerenovation',
            options={'verbose_name': 'Residence Renovation', 'verbose_name_plural': 'Residences Renovation'},
        ),
    ]
