# Generated by Django 2.1.1 on 2018-10-21 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Profile', 'verbose_name_plural': 'Profiles'},
        ),
        migrations.AlterField(
            model_name='profile',
            name='born_date',
            field=models.DateField(blank=True, null=True, verbose_name='Born date'),
        ),
    ]
