# Generated by Django 2.1.1 on 2018-10-24 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20181020_2233'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='occupation',
            field=models.CharField(choices=[('FAC', 'Functionary of Attention to Customer'), ('BAC', 'Boss of Attention to Customer'), ('BDAC', 'Boss of Departament of Attention to Customer'), ('DIR', 'Director'), ('ADMIN', 'Administrator')], default=('FAC', 'Functionary of Attention to Customer'), max_length=5, verbose_name='Occupation'),
        ),
    ]
