# Generated by Django 2.1.1 on 2018-11-05 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20181031_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='occupation',
            field=models.CharField(choices=[('FAC', 'Functionary of Attention to Customer'), ('BAC', 'Boss of Attention to Customer'), ('BDAC', 'Boss of Departament of Attention to Customer'), ('DIR', 'Director'), ('ADMIN', 'Administrator')], default='FAC', max_length=5, verbose_name='Occupation'),
        ),
    ]
